from typing import Protocol

from trafficmaster.application.common.query_params.pagination import Pagination
from trafficmaster.domain.deck.entities.deck import Deck
from trafficmaster.domain.deck.values.deck_config_id import DeckConfigID
from trafficmaster.domain.deck.values.deck_id import DeckID
from trafficmaster.domain.user.values.user_id import UserID


class DeckGateway(Protocol):
    async def add(self, deck: Deck) -> None: ...

    async def delete_by_id(self, deck_id: DeckID) -> None: ...

    async def read_by_id(self, deck_id: DeckID) -> Deck | None: ...

    async def read_by_user_id(self, user_id: UserID) -> list[Deck]: ...

    async def read_public_decks(self, pagination: Pagination) -> list[Deck]: ...

    async def count_by_user(self, user_id: UserID) -> int: ...

    async def exists_with_deck_config_id(self, deck_config_id: DeckConfigID) -> bool: ...
