from trafficmaster.domain.common.errors import DomainFieldError


class CardQuestionEmptyError(DomainFieldError): ...


class TooShortQuestionError(DomainFieldError): ...


class TooLongQuestionError(DomainFieldError): ...


class CardAnswerEmptyError(DomainFieldError): ...


class TooLongAnswerError(DomainFieldError): ...


class TooShortAnswerError(DomainFieldError): ...


class EmptyCardTagError(DomainFieldError): ...


class TooLongCardTagError(DomainFieldError): ...


class TooShortCardTagError(DomainFieldError): ...
