from trafficmaster.domain.common.errors import DomainFieldError


class CardQuestionEmptyError(DomainFieldError): ...


class TooShortQuestionError(DomainFieldError): ...


class TooLongQuestionError(DomainFieldError): ...


class TooLongAnswerError(DomainFieldError): ...


class TooShortAnswerError(DomainFieldError): ...


class EmptyAnswerOptionsError(DomainFieldError): ...


class InvalidCorrectAnswerCountError(DomainFieldError): ...


class TooLongAnswerOptionRationaleError(DomainFieldError): ...


class TooLongCardHintError(DomainFieldError): ...


class EmptyCardTagError(DomainFieldError): ...


class TooLongCardTagError(DomainFieldError): ...


class DuplicateCardTagError(DomainFieldError): ...


class CardTagNotFoundError(DomainFieldError): ...


class TooShortCardTagError(DomainFieldError): ...
