from trafficmaster.domain.common.errors import DomainFieldError


class DeckConfigNameEmptyError(DomainFieldError): ...


class NewGreaterThanReviewedError(DomainFieldError): ...


class TooBigCardLimitError(DomainFieldError): ...


class TooSmallCardLimitError(DomainFieldError): ...


class LearningIntervalGreaterGraduatingError(DomainFieldError): ...


class EasyIntervalLessThanGraduatingError(DomainFieldError): ...


class NotEnoughLearningStepsError(DomainFieldError): ...


class TooLowStepIntervalError(DomainFieldError): ...


class StepsNotIncreasingError(DomainFieldError): ...


class TooSmallLeechThresholdError(DomainFieldError): ...


class TooSmallMinRepeatIntervalError(DomainFieldError): ...


class TooLowMaxIntervalError(DomainFieldError): ...


class MinIntervalGreaterThanMaxIntervalError(DomainFieldError): ...


class TooLowEasyFactorError(DomainFieldError): ...


class InvalidIntervalModifierError(DomainFieldError): ...


class InvalidHardIntervalError(DomainFieldError): ...


class InvalidNewIntervalError(DomainFieldError): ...
