"""init schema

Revision ID: 426eaf5821c5
Revises:
Create Date: 2026-06-02 00:01:03.017188

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "426eaf5821c5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expiration", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("hashed_password", sa.LargeBinary(), nullable=False),
        sa.Column("role", sa.Enum("SUPERADMIN", "ADMIN", "USER", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "deck_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("new_cards_per_day", sa.Integer(), nullable=False),
        sa.Column("max_reviews_per_day", sa.Integer(), nullable=False),
        sa.Column("reviews_dont_bury_new", sa.Boolean(), nullable=False),
        sa.Column("learning_steps", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("graduating_interval", sa.Integer(), nullable=False),
        sa.Column("easy_interval", sa.Integer(), nullable=False),
        sa.Column("new_card_order", sa.Enum("SEQUENTIAL", "RANDOM", name="newcardorder"), nullable=False),
        sa.Column("relearning_steps", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("min_interval", sa.Integer(), nullable=False),
        sa.Column("leech_threshold", sa.Integer(), nullable=False),
        sa.Column("leech_action", sa.Enum("TAG_ONLY", "SUSPEND", name="leechaction"), nullable=False),
        sa.Column("max_interval", sa.Integer(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("easy_factor", sa.Float(), nullable=False),
        sa.Column("interval_modifier", sa.Float(), nullable=False),
        sa.Column("hard_interval", sa.Float(), nullable=False),
        sa.Column("new_interval", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("pg_deck_configs_owner_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deck_configs")),
    )
    op.create_table(
        "decks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("deck_config_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["deck_config_id"], ["deck_configs.id"], name=op.f("pg_decks_deck_config_id_deck_configs")
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("pg_decks_owner_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decks")),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("deck_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.String(length=5000), nullable=False),
        sa.Column("answer", sa.String(length=5000), nullable=False),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], name=op.f("pg_cards_deck_id_decks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
    )
    op.create_table(
        "card_progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("state", sa.Enum("NEW", "LEARNING", "REVIEW", "RELEARNING", name="cardstate"), nullable=False),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], name=op.f("pg_card_progress_card_id_cards")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("pg_card_progress_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_progress")),
        sa.UniqueConstraint("user_id", "card_id", name="uq_card_progress_user_id_card_id"),
    )
    op.create_table(
        "review_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Enum("AGAIN", "HARD", "GOOD", "EASY", name="reviewrating"), nullable=False),
        sa.Column("card_state", sa.Enum("NEW", "LEARNING", "REVIEW", "RELEARNING", name="cardstate"), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], name=op.f("pg_review_logs_card_id_cards")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("pg_review_logs_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_logs")),
    )
    op.create_index("ix_review_logs_card_id_reviewed_at", "review_logs", ["card_id", "reviewed_at"], unique=False)
    op.create_index("ix_review_logs_user_id_reviewed_at", "review_logs", ["user_id", "reviewed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_logs_user_id_reviewed_at", table_name="review_logs")
    op.drop_index("ix_review_logs_card_id_reviewed_at", table_name="review_logs")
    op.drop_table("review_logs")
    op.drop_table("card_progress")
    op.drop_table("cards")
    op.drop_table("decks")
    op.drop_table("deck_configs")
    op.drop_table("users")
    op.drop_table("auth_sessions")
    # ### end Alembic commands ###
