from typing import Protocol

from trafficmaster.application.auth.auth_model import AuthSession
from trafficmaster.domain.user.values.user_id import UserID


class AuthSessionGateway(Protocol):
    async def add(self, auth_session: AuthSession) -> None: ...

    async def update(self, auth_session: AuthSession) -> None: ...

    async def read_by_id(self, auth_session_id: str) -> AuthSession | None: ...

    async def delete(self, auth_session_id: str) -> None: ...

    async def delete_all_for_user(self, user_id: UserID) -> None: ...
