from trafficmaster.application.errors.base import ApplicationError


class UserNotFoundByEmailError(ApplicationError): ...


class UserAlreadyExistsError(ApplicationError): ...


class UserNotFoundByIdError(ApplicationError): ...


class NoPermissionToManageUserError(ApplicationError): ...


class EmailAlreadyExistsError(ApplicationError): ...
