from trafficmaster.domain.common.errors import DomainFieldError


class TooBigUsernameError(DomainFieldError): ...


class TooSmallUsernameError(DomainFieldError): ...


class UsernameCantBeEmptyError(DomainFieldError): ...


class BadUsernameError(DomainFieldError): ...


class WrongUserEmailFormatError(DomainFieldError): ...


class RoleAssignmentNotPermittedError(DomainFieldError): ...


class RoleChangeNotPermittedError(DomainFieldError): ...


class AccessChangeNotPermittedError(DomainFieldError): ...
